### ISSUE TITLE
DaVinci Intermediate IDT/ODT accuracy

### ISSUE THREAD

**Issue by antonmeleshkevich** [xtremestuff/resolve-aces#2]
Hi, Thatcher!
I found DaVinci Intermediate IDT/ODT DCTLs give some difference compared to CST.
These values give the identical match:

```
__CONSTANT__ float matrix[9] = {
     0.748270290270679f,  0.167694659549422f,  0.084035050222766f,
     0.020842123444419f,  1.111904742666049f, -0.132746866104714f,
    -0.091512257422527f, -0.127746712807242f,  1.219258970229265f,
};
```
```
// Used inverse of matrix from the IDT.
__CONSTANT__ float matrix[9] = {
     1.328323120016896f, -0.213523641303889f, -0.114799478824335f,
    -0.013160753845427f,  0.912865417908090f,  0.100295335979076f,
     0.098319230930014f,  0.079618463603444f,  0.822062305501921f,
};
```
(calculated using [this](https://www.colour-science.org:8010/apps/rgb_colourspace_transformation_matrix?input-colourspace=DaVinci+Wide+Gamut&output-colourspace=ACES2065-1&chromatic-adaptation-transform=CAT02&formatter=spimtx&decimals=15))

Or you've intentionally used some CAT different from CAT02?

**Comment by antonmeleshkevich** [comment]
Nevermind. Just noticed you've used Bradford :)

**Comment by antonmeleshkevich** [comment]
Nevermind. Just noticed you've used Bradford :)
Anyway, the calculator from the link above allows up to 15 decimals, so maybe you'll find it useful.

**Comment by antonmeleshkevich** [comment]
Wouldn't using CAT02 give more expected results?
Based on [this](https://community.acescentral.com/t/aces-and-chromatic-adaptation-consistency/5217) thread from ACESCentral?

**Comment by RikshaDriver** [comment]
Hi Anton,

This particular repo does not contain any DaVinci Intermediate IDT/ODTs.

Was this issue meant for a separate repo?

**Comment by antonmeleshkevich** [comment]
Oh, I'm sorry, you are totally right! It's a different repo.
